# Generated by Django 4.2.17 on 2025-03-07 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money', models.FloatField()),
                ('type_money', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10)),
                ('where', models.CharField(choices=[('O`tkazmalar', 'O`tkazmalar'), ('Taksi', 'Taksi'), ('Oziq-ovqat', 'Oziq-ovqat'), ('Komunal', 'Komunal'), ('Telefoniya', 'Telefoniya'), ('Transport', 'Transport'), ('Kosmetika', 'Kosmetika'), ('Online-Do`kon', 'Online-Do`kon'), ('Kiyim-Kechak', 'Kiyim-Kechak')], max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.foydalanuvchilar')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True)),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('money', models.FloatField(default=0)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.foydalanuvchilar')),
            ],
        ),
    ]
